### ISSUE TITLE
Draft agenda for WGTAFGOV

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/wg_WGTAFGOV#115]

**Comment by colinpmillar** [comment]
Proposed agenda items:

1. Impact of cyber attack
2. Update on tafXplorer app
3. Present process for publishing stocks in 2024
4. Present ToRs for new WKs
  * WK on stock assessment templates
  * WK on code review for stock assessments
  * WK on TAF training and templates for RDBES national estimators
5. Review project board and roadmap

**Comment by iagomosqueira** [comment]
6. Proposal for ASC 2025 session on TAF
