### ISSUE TITLE
Draft agenda for Q3 WGTAFGOV

### ISSUE THREAD

**Issue by iagomosqueira** [ices-eg/wg_WGTAFGOV#134]
- Reviewing and Publishing manifesto
- Progress on access rights
- Status of TAF server
- Increasing uptake of TAF #92

**Comment by iagomosqueira** [comment]
- Final review and publishing process for the TAF manifesto
- Actions to increasing uptake of TAF
- Relaunch TAF ambassador network
- Proposed WKs on TAF for 2025

**Comment by jensr** [comment]
Just wondering if there's an update from running the TAF stand at the ASC as well? Would be good to hear a bit about the engagement - and if any contacts or engagements might help with the ambassador network?

**Comment by iagomosqueira** [comment]
I think we are still waiting to hear about our proposal for 2025. @colinpmillar can you confirm?

**Comment by lucalamoni** [comment]
@jensr I can give a brief overview about the ASC and the apps presented at the stand.

**Comment by colinpmillar** [comment]
We have submitted it, and its in the system, but waiting to hear yes.

**Comment by iagomosqueira** [comment]
Sorry @jensr , confused this year's and next year's ASC. @lucalamoni , please do

**Comment by iagomosqueira** [comment]
- TAF ICES ASC 2024
  - Final review and publishing process for the TAF manifesto
  - Actions to increasing uptake of TAF
  - Relaunch TAF ambassador network
  - Proposed WKs on TAF for 2025
