### ISSUE TITLE
How is data published from a TAF repository

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/wg_WGTAFGOV#16]
# Summary

Does every repository need a DOI
Is the whole repository given a DOI

# task list

- [ ] consider the metadata requirements
- [ ] ...

# related issues

**Comment by nilsolav** [comment]
The APIs and standard outputs should also be a apart of this task.

**Comment by colinpmillar** [comment]
See manifesto - we will not publish eacg repository with a DOI
https://htmlpreview.github.io/?https://github.com/ices-eg/WGTAFGOV/blob/master/formatted_docs/taf_manifesto.html

If a subset of a data product from a TAF project is to be published, it is a separate process, much like publishing documents or 
reports. Alternatively, for the stock assessment TAF type, many of the end results will be published through the Stock 
Assessment Graphs database[7] (SAG), which creates a DOI per stock.

If the entire project (data, model, output) is to be formally published, the suggested metadata profile should support mandatory fields for DataCite DOI publication. However, it is not envisaged that TAF projects are formally published by default.
