### ISSUE TITLE
General improvement to Landing Page: Links etc.

### ISSUE THREAD

**Issue by arni-magnusson** [ices-eg/wg_WGTAFGOV#22]
Can we make the Gists page more visible, easier to find:
https://gist.github.com/ices-gists

**Comment by arni-magnusson** [comment]
Gists are perhaps not very straightforward for people to contribute to.

We could consider using a repository instead? The Gist format has some benefits, though...

**Comment by arni-magnusson** [comment]
ices.taf.dk should have a link to TAFGOV

**Comment by colinpmillar** [comment]
link to user handbook and new interface @colinpmillar  and @neil-ices-dk

**Comment by neil-ices-dk** [comment]
do we have a user handbook for TAF?

**Comment by colinpmillar** [comment]
it is priority 1 :) #14

**Comment by neil-ices-dk** [comment]
ok so what are we proposing to link to?

**Comment by nilsolav** [comment]
I think the web page should link to any relevant information of the TAF system. This includes the manifesto, the actual TAF system and the user manuals (to be produced). 

Nils Olav

**Comment by neil-ices-dk** [comment]
> 
> 
> I think the web page should link to any relevant information of the TAF system. This includes the manifesto, the actual TAF system and the user manuals (to be produced).
> 
> Nils Olav

fully agree - i just need the list of links (show me the money 💵 )

**Comment by nilsolav** [comment]
Merge/restructure this task with the user hand book task.?

**Comment by nilsolav** [comment]
Goal is to review the landingpage and the examples by nest tafgov meeting.

**Comment by colinpmillar** [comment]
@colinpmillar and @cekv to arrange meeting with @neil-ices-dk to update landing page

**Comment by cekv** [comment]
The Landing page has changed, but is not published yet, a few more things are needed but will be ready by beginning of June.

**Comment by neil-ices-dk** [comment]
screen grab of new version 
![image](https://user-images.githubusercontent.com/23527005/168018728-bc9f2054-07d7-4e1a-bd4d-8245537ffd32.png)

@cekv it might be a good time to refresh with a new image in the top right

**Comment by cekv** [comment]
New landing page done and published
