### ISSUE TITLE
ICES news article on TAF

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/wg_WGTAFGOV#24]
### Summary

* **background intro** information flow diagram and a very short introduction
* **Training Workshops**, who are we doing them for, who many have we done and any in the pipeline
* **What is TAF being used for**
  * Stock assessments and forecasts
  * Mixed fisheries
  * survey index calculations
  * Fisheries overviews
  * Some technical services and special requests
* Currently working on **acoustic index calculations** (worked on this at WKTAF-SNS last week)
* **RDBES** is working on using TAF to run raising procedures on commercial catch data
* Formation of **WGTAFGOV** and this GitHub page

### task list

- [x] get feedback from group by end of week 26th June 
- [x] @Terhinator will draft during next week (begining 29th june)

**Comment by jensr** [comment]
Looks good to me in terms of topics - Is TAF well enough established now that we assume everyone knows what it is - or is it still work including the information flow diagram and a very short introduction?

**Comment by colinpmillar** [comment]
https://github.com/ices-eg/WGTAFGOV/issues/24#issuecomment-648731294 good idea! Have updated the list

**Comment by clordan** [comment]
I would also profile other advice products using TAF e.g WGSFD. Otherwise looks good.

**Comment by neil-ices-dk** [comment]
Hi Colin/Arni - is it a news article or a newsletter you are aiming for; the above list is good and comprehensive but it doesn't have a specific focus, other than generally highlighting TAF and the ongoing work. This is fine, if this is what you intend. You could also consider a different approach and focus in on either a specific (new) use case or something topical i.e. the 3 most commonly asked questions that the workshops have generated.

**Comment by Terhinator** [comment]
Hi Neil, we were thinking of writing a news article which can be published in the beginning of July. It can also be included in the July newsletter, which won't be out until the end of the month, if you think that's useful?
I like the idea of 3 most commonly asked questions - will talk to Colin & Arni about that!

**Comment by neil-ices-dk** [comment]
thanks @Terhinator - you missed my point on the newsletter, what i meant was the table of contents above looks like a standalone TAF newsletter ;)

**Comment by Terhinator** [comment]
Ah, ok :P I like your "3 questions" approach, so I'll work with that with Colin & Arni :)

**Comment by colinpmillar** [comment]
I think we will produce two items from this issue
1. a fun article that piques peoples interest for the website
2. A more comprehensive "TAF news letter / flyer"

We will do 1. just now, and 2. after summer

**Comment by colinpmillar** [comment]
Coming back to this:
Contact Celine about TAF news letter.

**Comment by colinpmillar** [comment]
Recieved nice comments from three users about the TAF and the workshops :) will be putting these out on social media rather than a short article

**Comment by neil-ices-dk** [comment]
I've just had Celine in my office wanting input for the ICES annual report (for tomorrow....). So if you have something you want to shout about i.e. establishment of WGTAFGOV or the manifesto or the workshops etc. then write a few sentences and we'll send it on ✍️
