### ISSUE TITLE
Maintain a rotating list of training workshops

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/wg_WGTAFGOV#29]
### Summary

Create a list of workshops and proposed dates.

**Comment by colinpmillar** [comment]
Current list of planned and proposed workshops

* WKTAF for acoustic indices (will be part of WGIPS) - Jan 2021
* WKTAF for WGMIXFISH - Feb 2021
* WKTAF for ACOM - 1st quarter 2021
* WKTAF for AFWG - TBD
* WKTAF for Fisheries and Ecosystem overviews - TBD

**Comment by nilsolav** [comment]
We are using the project board to maintain the rotating list and use the training label.

**Comment by colinpmillar** [comment]
Here is the filter applied to the project board:

https://github.com/ices-eg/wg_WGTAFGOV/projects/1?card_filter_query=label%3A%22area%3A+5.+training%22
