### ISSUE TITLE
"Bootstrap" and "model"

### ISSUE THREAD

**Issue by nilsolav** [ices-eg/wg_WGTAFGOV#33]
### Summary
The use of the terms "bootstrap" and "model" in the TAF repos are either to limited or may cause confusion.

We have also had a request from some in the RDBES-EST group to rename “model” to “method” or “estimation” to reflect that some repos will be running design based estimators not model based, but most repos will be doing some form of estimation or applying a method of some kind. We propose to rename "model" to "method" to allow for other TAF methods, like survey estimation etc.

Bootstrap is a established term in statistics and is also used for preparing data. We suggest to rename "boostrap" to "boot method" or "assemble method". 

Please add any comments by Nov 10th 2020, and we will proceed with the changes.

### task list

- [ ] ...
- [ ] ...

**Comment by iagomosqueira** [comment]
I quite favor `boot.R`, as a shorter substitute for `bootstrap.R`.

Another option starting with B is `build.R`.

And better keep it as one word, no spaces in filenames is much safer in Linux and R.

**Comment by nilsolav** [comment]
> 
> 
> I quite favor `boot.R`, as a shorter substitute for `bootstrap.R`.
> 
> Another option starting with B is `build.R`.
> 
> And better keep it as one word, no spaces in filenames is much safer in Linux and R.

Agree. And by using "boot" we will also keep the "history" and avoid creating further confusion.

**Comment by iambaim** [comment]
I seconded `boot`. Like when we `boot`a computer, except here we `boot` the DATRAS environment.

**Comment by iagomosqueira** [comment]
Could we maybe get this changed in time for the [ICES TC on TAF](https://www.ices.dk/events/Training/Pages/TAF.aspx)?

**Comment by colinpmillar** [comment]
Yes, I think we should set a date and then switch everything over on that date. Given that the TC is now august time, the main consideration is to be before or after the advice season. So, what do we think?

**Comment by PatrickLynch-NOAA** [comment]
Bootstrap changed to Boot
Model changed to Method

**Comment by colinpmillar** [comment]
If done, send message to user that bootstrap and model are depreciated. and switch to boot and method.

**Comment by colinpmillar** [comment]
Concerns that there are many dependencies, i.e. training material presentations.

**Comment by colinpmillar** [comment]
we recognise the problem with the terminology, but it is not a high priority at the moment.
