### ISSUE TITLE
Survey of TAF adopters and non-adopters

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/wg_WGTAFGOV#43]
### Summary
online user survey: to identify the top 3 hurdles i.e. habits, missing functions, skills, training etc. 

### basic information

1. Who they are [email address]
2. Role (drop down): stock coordinator; assessment coordinator; other (free text)
3. stocks (drop down list) - multiple select
4. Are you a current user of taf.ices.dk? Yes; No; i have logged in but not used it; 

### questions: 
5. What are the main barriers for you in using TAF?; [likert scale](https://en.wikipedia.org/wiki/Likert_scale)
option list: (multiple answers)
- not comfortable in using Git
- not comfortable in using GitHub
- scripting using R
- lack of guidance or training for using TAF
- technical setup issues
- lack of time to use it
- the system is not mature enough
- unclear on the time investment required or the benefits
- i prefer an online app one-click solution 
- i can't directly export into sag.ices.dk (stock assessment graphs)

6. What are the main advantages for you in using TAF in its current form? [likert scale](https://en.wikipedia.org/wiki/Likert_scale)
- documentation of my code
- easier to share workload in assessment
- version control
- ensuring scripts are robust (error free?)
- input data are documented
- automation of the assessment run

7. What would you most like to see further developed in TAF? [likert scale](https://en.wikipedia.org/wiki/Likert_scale)
- direct export into sag.ices.dk
- online training via short video tutorials
- more hands-on workshops
- helpdesk support
- online documentation
- web app (allowing easy use without coding expertise)
- copying a stock instance from one year to the next
- review of stock in TAF by ADG

**Comment by neil-ices-dk** [comment]
@nilsolav, @clordan, @ghislainices, @Lotte-ices-dk can you take a look at the above and make any edits or comments so we can then setup a short survey to capture this information - thanks (Neil and Colin)

**Comment by nilsolav** [comment]
Re point 6: Perhaps add something about the advantage of i) piping the information through to SAG, ii) automatic reporting, and possibly other carrots?

**Comment by ghislainices** [comment]
Hi,
Regarding question 5: maybe add the following:  unclear on the time investment required or the benefits.
Aside from that, it looks good to me.
Ghislain

**Comment by neil-ices-dk** [comment]
> 
> 
> Hi,
> Regarding question 5: maybe add the following: unclear on the time investment required or the benefits.
> Aside from that, it looks good to me.
> Ghislain

Thanks Ghislain, now added to Q5 👍

**Comment by Lotte-ices-dk** [comment]
Looks good - could we add something along the lines of TAF becoming a tool where you don't necessarily need to be a super-coder in order to use it? Just said more elegantly...

**Comment by Lotte-ices-dk** [comment]
@neil-ices-dk, cool, then yes, it should be spelled out ;-)

**Comment by neil-ices-dk** [comment]
> 
> 
> @neil-ices-dk, cool, then yes, it should be spelled out ;-)

@Lotte-ices-dk care to suggest a phrasing?

**Comment by neil-ices-dk** [comment]
😢 😢  HR have been alerted 👮 

in the meantime i have updated the survey 🥇

**Comment by clordan** [comment]
7. Direct export of outputs into advice sheets\products and EG reports

**Comment by neil-ices-dk** [comment]
> 
> 
>     1. Direct export of outputs into advice sheets\products and EG reports

@colinpmillar and @clordan how does this relate to SAG; if the process is TAF->SAG->Advice Sheet would this in part answer that development, and are we really talking here about full mark down reports for EG's etc. which would require an entirely new process away from the traditional EG pubs templates

**Comment by neil-ices-dk** [comment]
hello @nilsolav, @clordan, @ghislainices, @Lotte-ices-dk and @colinpmillar the draft survey is online and ready for a test run - could you try and fill it out and reply in here if anything needs adjusting - thanks!

[TAF survey draft](https://forms.office.com/r/2jJenZemZK)

**Comment by nilsolav** [comment]
I added my  (more or less) random response. I think this looks good.

Nils Olav

**Comment by neil-ices-dk** [comment]
thanks all, looks like it works 📈 

@colinpmillar will you liaise with Jette next week to get this broadcasted on all frequencies 📶 

![image](https://user-images.githubusercontent.com/23527005/119982273-eb75f600-bfbe-11eb-8644-0df198fff8d9.png)

**Comment by nilsolav** [comment]
Do we set a time line? I think it would be good to have a WGTAFGOV meeting after the deadline, and ideally before the summer holidays. Suggestions?

Nils Olav

**Comment by neil-ices-dk** [comment]
when are summer holidays in Norway - we can then work the timeline backwards from that? @nilsolav

**Comment by JetteFredslund** [comment]
Hello everyone - I'm being asked (internally) for dates for the public meeting calendar - have you guys decided on the next meeting date?

**Comment by nilsolav** [comment]
I will leave for holiday June 25th. I suggest a TAFGOV meeting between 21st to 25th. Here's a doodle: https://doodle.com/poll/bcc6vk4swg3t6m76?utm_source=poll&utm_medium=link

**Comment by neil-ices-dk** [comment]
survey is now out on social media and by email, the link is here if you want to target anyone specifically:

[https://forms.office.com/r/2jJenZemZK](https://forms.office.com/r/2jJenZemZK)

We already have 21 responses, and a picture is starting to emerge:

![image](https://user-images.githubusercontent.com/23527005/121517358-917a2500-c9ef-11eb-8011-8c7d756f8564.png)

**Comment by neil-ices-dk** [comment]
preliminary findings compiled in presentation for June '21 TAFGOV meeting 
[presentation of TAF Survey](http://community.ices.dk/ExpertGroups/WGTAFGOV/2020%20Meeting%20Docs/05.%20Presentations/TAF-survey-18JUNE2021.pptx)

**Comment by JetteFredslund** [comment]
Hello all - I had a look at the doodle Nils Olav posted above. It looks like everyone is available Monday 21 June - would you like to set that date in stone?
Jette

**Comment by neil-ices-dk** [comment]
@JetteFredslund Colin is not available on Monday 21

**Comment by JetteFredslund** [comment]
> @JetteFredslund Colin is not available on Monday 21

Do you know if he is available Friday 25? That's the next best option. However, Iago cannot make that date. Would be good to settle on a date soon, right?

**Comment by neil-ices-dk** [comment]
@iagomosqueira to follow-up on the analysis of those that claimed lack of time:

- for the small sample of non-users the response is mixed
- for the stock assessors, there is a clear signal that 'time' in whatever way that is meant is an issue

![image](https://user-images.githubusercontent.com/23527005/122557054-8e5ce580-d03c-11eb-9fc1-c099910ec125.png)

**Comment by neil-ices-dk** [comment]
News piece and call to action on ices.dk 
[https://www.ices.dk/news-and-events/news-archive/news/Pages/TAF.aspx](https://www.ices.dk/news-and-events/news-archive/news/Pages/TAF.aspx)

will be re-run so it appears at the top of the newsfeed for the next few weeks at least; do we have an idea of how many responses we would consider as acceptable - 50, 75??

![image](https://user-images.githubusercontent.com/23527005/122564037-34ace900-d045-11eb-943a-1cf2853e1dbb.png)

**Comment by iagomosqueira** [comment]
I should be available for a call on Friday 25

**Comment by colinpmillar** [comment]
I can do the 25th. SOrry for the lack of response up till now!

**Comment by neil-ices-dk** [comment]
updated results from TAF survey, now with **42** responses, which has not changed the signals since the June snapshot. 
[06 JULY Presentation of TAF survey](url)http://community.ices.dk/ExpertGroups/WGTAFGOV/2020%20Meeting%20Docs/05.%20Presentations/TAF-survey-06JULY2021.pptx
