### ISSUE TITLE
WKTAF proposal going forward

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/wg_WGTAFGOV#59]
Propose a way to capture as wide an audience (but still manageable)

Currently the way we work is to offer a 2 day workshop to an EG, covering Github, gettting data sets into TAF, getting models into TAF, then outputs and plots.

**Comment by colinpmillar** [comment]
Idea:
* survey stock assessment EGs with three questions, do they need help with:
  - GitHub
  - R and icesTAF package
  - Getting data into TAF
  - Running thier model in TAF
  - Creating TAF and SAG outputs
* also ask what model they are using so we can group together people with the same type of model issues (e.g. uses an executable)

**Comment by cekv** [comment]
Link to survey:
https://www.surveymonkey.com/r/LZS83JC

**Comment by colinpmillar** [comment]
Proposal from @jensr to hold quarterly workshops on GitHub etc.

@iago suggests trying to pull in advanced users to help

**Comment by nilsolav** [comment]
Plan:
-4 workshops per year
-Different topics planned for each day/time slot so that people can pick and choose according to their needs.
-The timing for the workshops should be aligned with the working groups. Coordinate the timing with the ACOM professional officers.

**Comment by colinpmillar** [comment]
possibly approach the TAF reporting ambassadors for help with WKTAF
https://github.com/orgs/ices-taf/teams/taf-reporting-ambassadors/members

**Comment by cekv** [comment]
Survey sent to stock assessors regarding their requirements for upcoming TAFWKs, the responses so far has given an indication of at least 3 TAF WKs for 2022 with different TAF requirement. 
Also, per request - during Benchmark WKs at least half a day will be set aside for a TAF presentation and assistance with TAF.

**Comment by colinpmillar** [comment]
We should work to open up the intro sessions given to Benchmark groups to a wide audience. SInce these are online anyway, we can invite people to watch and listen in to these sessions. Or simply make them fully open and advertise

**Comment by colinpmillar** [comment]
note: include slides on the DIG data profiling tool

**Comment by colinpmillar** [comment]
links to previous requests for TAF WKs:
* #57
* #47 
* #48 
* #49 
* #50 
* #51

**Comment by cekv** [comment]
![image](https://user-images.githubusercontent.com/75067038/153838942-cbd548c4-4f4a-4044-ad05-1ac4546e1ae1.png)

**Comment by cekv** [comment]
![WKTAF_Agenda_draft](https://user-images.githubusercontent.com/75067038/167837329-65914980-4a7b-4255-8a52-6efc4546adbd.png)

**Comment by colinpmillar** [comment]
* Finalise dates
* Advertise via POs
* Make a page on TAF WKs and link to it from the new TAF landing page

**Comment by cekv** [comment]
The first WKTAF was held on the 14 and 15 June.  There were 16 participants from 10 countries. 
Next will be held the 13 and 14 of September. A third will be scheduled at the beginning of 2023 (probably February).
