### ISSUE TITLE
TAF dashboard

### ISSUE THREAD

**Issue by cekv** [ices-eg/wg_WGTAFGOV#64]
Update dashboard as a shiny application.

This will be more efficient because:
* there are more possibilities for collaboration and support in terms of coding
* reduces workload on the web programming side (ASP NET Core)
* there are more resources to borrow from when updating / adding new features
* can be published on the new ICES shiny cloud server (shiny.io)

Work required:
- [ ] api to provide commits and file tree for TAF repos
- [ ] shiny app to present the info in these apis

**Comment by colinpmillar** [comment]
A proposal was made to use the dashboard as a means to assess the state of TAF with respect to the TAF manifesto - a helicopter view

**Comment by colinpmillar** [comment]
Hi, I have posted a draft dashboard here:
https://ices-taf.shinyapps.io/taf-dashboard/

Current functionality: plots the number of 'complete' assessments by stock in TAF and the total number stocks for a given year. along with a breakdown of stocks implemented by EG.

Other available data:
* file names and details (size)
* commits dates and authors.

Comments and suggestions would be great.

Comments and

**Comment by PatrickLynch-NOAA** [comment]
Hi Colin...this looks like a pretty slick and simple way to track progress. Would it be useful to also have a cumulative plot? If I understand it, you're plotting a bar for the total number of stocks assessed in a given year, and another denoting those entered in TAF in that year, right? I'm thinking another plot could be the total number of stocks assessed by ICES across years and the total of those that have a TAF repo. I could see this getting complicated by changes in stock structure, so maybe that's too hard to overcome. Anyway, nice work!

**Comment by colinpmillar** [comment]
Mark has created a plot from the data which I think we should include on the dashboard:
![image](https://user-images.githubusercontent.com/1502848/169801221-7aed7c56-b6e5-4073-9b4e-2b786fbee174.png)

I will add it and we can see what others think
