### ISSUE TITLE
publish Bay of Biscay and Iberian coast, Celtic Seas, and North Sea fish stock TAF repos

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/wg_WGTAFGOV#99]
https://www.ices.dk/advice/Pages/advice_release_dates.aspx

**Comment by colinpmillar** [comment]
- [ ] Get list of stocks to publish TAF code for, and provide links to everyone for the advice sheet

**Comment by sarahlmillar** [comment]
@colinpmillar  the WGNSSK chairs sent you an email with the stocks we need links for  -i will forward it to you again, but let me know if you want it copied in here
